-- MySQL Script generated by MySQL Workbench
-- sáb 04 ago 2018 15:16:07 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

Create database wefit;
USE `wefit` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------



CREATE TABLE IF NOT EXISTS `Usuario` (
  `Cedula` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` TINYINT(4) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Altura` TINYINT(4) NOT NULL,
  `Grasa` VARCHAR(45) NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Maquina` (
  `idMaquina` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Animacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaquina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entrenador` (
  `Cedula` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Animacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEjercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inscripcion` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(45) NOT NULL,
  `Cedula` INT NOT NULL,
  `Meses` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInscripcion`),
  INDEX `fk_Inscripcion_Usuario_idx` (`Cedula` ASC),
  CONSTRAINT `fk_Inscripcion_Usuario`
    FOREIGN KEY (`Cedula`)
    REFERENCES `Usuario` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rutina` (
  `idRutina` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `idInscripcion` INT NULL,
  PRIMARY KEY (`idRutina`),
  INDEX `fk_RutinaDiaria_Inscripcion1_idx` (`idInscripcion` ASC),
  CONSTRAINT `fk_RutinaDiaria_Inscripcion1`
    FOREIGN KEY (`idInscripcion`)
    REFERENCES `Inscripcion` (`idInscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RutinaDiaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RutinaDiaria` (
  `idRutinaDiaria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `idRutina` INT NOT NULL,
  `idEjercicio` INT NOT NULL,
  INDEX `fk_Rutina_RutinaDiaria1_idx` (`idRutina` ASC),
  INDEX `fk_RutinaDiaria_Ejercicio1_idx` (`idEjercicio` ASC),
  CONSTRAINT `fk_Rutina_RutinaDiaria1`
    FOREIGN KEY (`idRutina`)
    REFERENCES `Rutina` (`idRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RutinaDiaria_Ejercicio1`
    FOREIGN KEY (`idEjercicio`)
    REFERENCES `Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
